version: '3.8'

services:
  weather-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    volumes:
      - ./public:/usr/src/app/public
    restart: unless-stopped 